# Shared Models
# Pydantic models and SQLAlchemy models used across services

from .base import (
    BaseSchema,
    TimestampMixin,
    ResponseModel,
    PaginatedResponse,
    HealthCheckResponse,
    ErrorResponse,
)

from .user import (
    UserRole,
    UserStatus,
    UserBase,
    UserCreate,
    UserUpdate,
    User,
    UserPublic,
    UserLogin,
    UserLoginResponse,
    RefreshTokenRequest,
)

from .market_data import (
    Exchange,
    SymbolType,
    MarketStatus,
    Quote,
    OHLCV,
    HistoricalData,
    ScreenerCriteria,
    ScreenerResult,
    MarketStatusResponse,
    MarketCalendar,
)

from .watchlist import (
    WatchlistBase,
    WatchlistCreate,
    WatchlistUpdate,
    Watchlist,
    WatchlistPublic,
    WatchlistItemBase,
    WatchlistItemCreate,
    WatchlistItemUpdate,
    WatchlistItem,
    WatchlistItemPublic,
    WatchlistWithItems,
)

from .trading import (
    OrderType,
    OrderSide,
    OrderStatus,
    GTTType,
    GTTStatus,
    AlertType,
    AlertStatus,
    Alert,
    AlertCreate,
    AlertUpdate,
    GTTOrder,
    GTTOrderCreate,
    GTTOrderUpdate,
    PortfolioItem,
    Portfolio,
    Trade,
)

__all__ = [
    # Base models
    "BaseSchema",
    "TimestampMixin",
    "ResponseModel",
    "PaginatedResponse",
    "HealthCheckResponse",
    "ErrorResponse",
    # User models
    "UserRole",
    "UserStatus",
    "UserBase",
    "UserCreate",
    "UserUpdate",
    "User",
    "UserPublic",
    "UserLogin",
    "UserLoginResponse",
    "RefreshTokenRequest",
    # Market data models
    "Exchange",
    "SymbolType",
    "MarketStatus",
    "Quote",
    "OHLCV",
    "HistoricalData",
    "ScreenerCriteria",
    "ScreenerResult",
    "MarketStatusResponse",
    "MarketCalendar",
    # Watchlist models
    "WatchlistBase",
    "WatchlistCreate",
    "WatchlistUpdate",
    "Watchlist",
    "WatchlistPublic",
    "WatchlistItemBase",
    "WatchlistItemCreate",
    "WatchlistItemUpdate",
    "WatchlistItem",
    "WatchlistItemPublic",
    "WatchlistWithItems",
    # Trading models
    "OrderType",
    "OrderSide",
    "OrderStatus",
    "GTTType",
    "GTTTStatus",
    "AlertType",
    "AlertStatus",
    "Alert",
    "AlertCreate",
    "AlertUpdate",
    "GTTOrder",
    "GTTOrderCreate",
    "GTTOrderUpdate",
    "PortfolioItem",
    "Portfolio",
    "Trade",
]
